# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update and upgrade APT repositories
RUN apt-get update && apt-get upgrade -y

# Run a command when the container starts to echo "Hello, World!"
CMD ["echo", "Hello, World!"]
